### PR TITLE
Change color tone on the help field status

### PR DESCRIPTION
**Pull request by harlekoy**
Warning 
image
Danger
image
Info
image

### CODE REVIEW

**Comment by harlekoy** [comment]
I have referenced this in TailwindCSS

**Comment by harlekoy** [comment]
Would love to have this cause the current color especially the warning color is kinda bright to the eyes

**Comment by harlekoy** [comment]
image
image


This is also how Laravel Nova badge is being displayed. It would be nice to have on the same color tone.

**Comment by micc83** [comment]
Hello @harlekoy thank you for your PR. I agree with you on this, but before accepting it I need to update all the screenshots in the readme file for consistency. It might take a while to do so. Also, what about adding a `success` type? Would it be useful?

**Comment by harlekoy** [comment]
Hey @micc83, yes I can include a `success` type in my PR. Let me know cause I will update my PR to make it easy for you.

**Comment by micc83** [comment]
That would be great. Thank you.

**Comment by harlekoy** [comment]
image
Hey @micc83 I updated my PR. Kindly check

**Comment by harlekoy** [comment]
```php
Help::info('Test')
    ->types([
        // Override all the available types classes
        'info' => 'bg-black text-white',
    ]);

Help::info('Test')
    ->addTypes([
       // Add to the types list, right now we don't have a way to use this custom type
        'dark-theme' => 'bg-black text-white',
    ]);
```
Also I added some new function that we can utilize and its the same how Laravel Nova Badge is being implemented.

**Comment by micc83** [comment]
Hello @harlekoy thank you. I'll check it out and publish a new release asap.

**Pull request merged**
