### PR TITLE
Support Nova 4 and php 8+

### LINKED ISSUE #21: Compatibility Nova 4 ?
Is it compatible with nova 4 ?
I have an issue with jsonSerialize() :(

### PR DESCRIPTION
**Pull request by max-zu**
Support Nova 4 and php 8+

### CODE REVIEW

**Comment by micc83** [comment]
Hi @max-zu, thank you for the PR. Unfortunately we still haven't bought a license for Nova 4 so we have no way to test it out.

**Comment by bogomya** [comment]
@micc83 , just tested, works fine, can we create a draft release, so then it will be available for everyone to use ?

**Comment by micc83** [comment]
Hello @bogomya, sure and yet we don't feel comfortable releasing a new prod version without having tested it accurately. We're thinking about releasing an alpha so that anyone can decide whether it is worth the risk.

**Comment by bogomya** [comment]
Hi @micc83 , thanks, would be really nice to have an alfa version to start using `nova-help` with Nova 4

**Comment by micc83** [comment]
Until we figure out next steps to take I merged it with the develop branch so it can be used with dev-develop.

**Comment by micc83** [comment]
We've also released [0.6.0-alpha](https://packagist.org/packages/comodolab/nova-help#0.6.0-alpha).

**Comment by tassilogroeper** [comment]
Thanks @micc83 for the release. As far as I can tell, the styling is broken, due to the change to inertia and Tailwinds JIT in nova-4. The current solution should be Scoped Styles, as described by @jimarick

https://github.com/laravel/nova-issues/issues/4061#issuecomment-1108865028

**Comment by micc83** [comment]
@tassilogroeper Unfortunately by now we're pretty sure we'll not invest anymore in the upgrade to Nova 4 or, more in general, in the development of the plugin. We're currently looking for a new trusted maintainer to transfer the project. I'll update you all as soon as I have some news. Thank you for your interest.

**Pull request merged**
